### ISSUE TITLE
Bug: the extension doesn't show up in 3DSlicer drop down menu

### ISSUE THREAD

**Issue by mingrui** [SBU-BMI/SlicerPathology#101]
3D Slicer 4.8.1

```
Number of registered modules: 144 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mingrui/.config/NA-MIC/Extensions-26813/SlicerPathology/lib/Slicer-4.8/qt-scripted-modules/SlicerPathology.py", line 749, in <module>
    red_logic = slicer.app.layoutManager().sliceWidget("Red").sliceLogic()
AttributeError: 'NoneType' object has no attribute 'sliceWidget'
loadSourceAsModule - Failed to load file "/home/mingrui/.config/NA-MIC/Extensions-26813/SlicerPathology/lib/Slicer-4.8/qt-scripted-modules/SlicerPathology.py"  as module "SlicerPathology" ! 
Fail to instantiate module  "SlicerPathology" 
Number of instantiated modules: 143 
Number of loaded modules: 143 
```

![selection_039](https://user-images.githubusercontent.com/699276/38599620-c7bb5652-3d93-11e8-94ef-54f1f4cece5a.png)

**Comment by mingrui** [comment]
found this solution similar to this, the problem is with indentation, you need to use 4 spaces as indentation on these lines:

(Do NOT follow solution in this thread, if you comment out these lines, you won't be able to load png files.)
https://discourse.slicer.org/t/pathology-module-install-fail-due-to-slicewidget-attribute-error/2269

This is the correct solution, just indent these lines
![selection_040](https://user-images.githubusercontent.com/699276/38611475-573b9af4-3db6-11e8-8cd8-0f84e5f2e965.png)
