### ISSUE TITLE
Runtime error - 'module' object has no attribute 'EditorWidget'

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#35]
While running the module packaged on Mac, I get the following runtime error

```
Adding WIP Button!
adding this for now...
to be implemented...
TCGA-XJ-A9DX-01Z-00-DX1_appMag_40_29_38-256x256_gray
to be implemented...
Preparing Quick TCGA Interaction
Traceback (most recent call last):
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 199, in onStartBot
    TCGASegBot(self)
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 251, in __init__
    self.start()
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 255, in start
    self.logic = ShortCutLogic( self.redSliceWidget.sliceLogic() )
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 332, in __init__
    slicer.modules.EditorWidget.removeShortcutKeys()
AttributeError: 'module' object has no attribute 'EditorWidget'
```

No idea why this is happening only in the binary version of Slicer (it apparently worked on the developer build).

cc: @pieper - any suggestions here?

**Comment by fedorov** [comment]
Code line in question:

https://github.com/SBU-BMI/SlicerPathology/blob/master/ShortCutEffect/ShortCutEffect.py#L332

**Comment by pieper** [comment]
slicer.modules.EditorWidget is only created when you enter the Editor
module itself so you should check if it exists before using it.

**Comment by naucoin** [comment]
@fedorov @pieper Pull request with a patch: https://github.com/SBU-BMI/SlicerPathology/pull/40

**Comment by fedorov** [comment]
not reproducible
