### ISSUE TITLE
Runtime error - possible packaging problems

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#36]
While running the module packaged on Mac, I get the following runtime error

```
>>> Adding WIP Button!
adding this for now...
to be implemented...
TCGA-XJ-A9DX-01Z-00-DX1_appMag_40_29_38-256x256_gray
to be implemented...
Preparing Quick TCGA Interaction
 key to run QuickTCGA segmentation is  Y
Traceback (most recent call last):
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/QuickTCGAEffect.py", line 244, in onStartBot
    TCGASegBot(self)
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/QuickTCGAEffect.py", line 297, in __init__
    self.start()
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/QuickTCGAEffect.py", line 301, in start
    self.logic = QuickTCGAEffectLogic( self.redSliceWidget.sliceLogic() )
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/QuickTCGAEffect.py", line 467, in __init__
    self.init_QuickTCGA()
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/QuickTCGAEffect.py", line 549, in init_QuickTCGA
    import vtkSlicerQuickTCGAModuleLogicPython
ImportError: No module named vtkSlicerQuickTCGAModuleLogicPython
Press key F to enable editing ShortCut region
startXYPosition
(137, 299)
currentXYPosition
(137, 299)
================================
Traceback (most recent call last):
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/QuickTCGAEffect.py", line 236, in onStartBot
    slicer.modules.TCGAEditorBot.stop()
  File "/Applications/Slicer-4.5.0-1/Slicer.app/Contents/Extensions-25042/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/QuickTCGAEffect.py", line 305, in stop
    self.logic.destroy()
AttributeError: 'TCGASegBot' object has no attribute 'logic'
Press key F to enable editing ShortCut region
startXYPosition
(143, 294)
currentXYPosition
(143, 294)
================================
```

@naucoin I expect that you are checking the packaged extensions and investigate this kind of issues.

**Comment by fedorov** [comment]
confirmed working on mac
