### ISSUE TITLE
ShortCutEffect: "could not convert string to float" runtime error

### ISSUE THREAD

**Issue by fedorov** [SBU-BMI/SlicerPathology#42]
```
Adding WIP Button!
adding this for now...
to be implemented...
TCGA-XJ-A9DX-01Z-00-DX1_appMag_40_29_38-256x256_gray
to be implemented...
Preparing Quick TCGA Interaction
 keys to run ShortCutCore segmentation, ShortCut, edit ShortCut, edit seed, reset parameters are S, C, F, E, R
Traceback (most recent call last):
  File "/Users/fedorov/local/builds/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 199, in onStartBot
    TCGASegBot(self)
  File "/Users/fedorov/local/builds/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 251, in __init__
    self.start()
  File "/Users/fedorov/local/builds/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 255, in start
    self.logic = ShortCutLogic( self.redSliceWidget.sliceLogic() )
  File "/Users/fedorov/local/builds/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 344, in __init__
    self.init_ShortCutCore()
  File "/Users/fedorov/local/builds/SlicerPathology/lib/Slicer-4.5/qt-scripted-modules/ShortCutEffect.py", line 441, in init_ShortCutCore
    otsuRatio = float(node.GetParameter("ShortCut,otsuRatio"))
ValueError: could not convert string to float: 
```

**Comment by fedorov** [comment]
Verifying from python console, indeed "ShortCut,otsuRatio" parameter is not present in the Editor parameter node. See steps to reproduce in the screenshot below. @ebremer please investigate.

![image](https://cloud.githubusercontent.com/assets/313942/15047564/7b174476-12b3-11e6-95b5-9b6259683858.png)

**Comment by naucoin** [comment]
@fedorov  and @ebremer  I was trying to debug something else and put in a quick patch to get around this error, pull request is https://github.com/SBU-BMI/SlicerPathology/pull/43

**Comment by naucoin** [comment]
Fixed by:
https://github.com/SBU-BMI/SlicerPathology/pull/43
